services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - $APPDATA/jellyfin/config:/config
      - $HOME/media/jellyfin:/media
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == brahma  # Ensure this service runs on the manager node
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.jayrup.me`)"
        - "traefik.http.routers.jellyfin.entrypoints=https"
        - "traefik.http.routers.jellyfin.tls=true"
        - "traefik.http.routers.jellyfin.tls.certresolver=myresolver"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      restart_policy:
        condition: on-failure

networks:
  traefik:
    external: true
